// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgOD7guIpr7mdCFRTmexdMA6WQvTgHYE',
    appId: '1:248469945081:web:a203e4ad90661387d6c028',
    messagingSenderId: '248469945081',
    projectId: 'todo-app-3f236',
    authDomain: 'todo-app-3f236.firebaseapp.com',
    storageBucket: 'todo-app-3f236.appspot.com',
    measurementId: 'G-SS6EYXW9QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfHbu-jbcSntEpxNaDtuBr1iBlvBQVrOM',
    appId: '1:248469945081:android:eff856fbf4f55a3ad6c028',
    messagingSenderId: '248469945081',
    projectId: 'todo-app-3f236',
    storageBucket: 'todo-app-3f236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMy2zqA2GnlIVevx2LtW2mePp4gG3frBo',
    appId: '1:248469945081:ios:473b00b49495e135d6c028',
    messagingSenderId: '248469945081',
    projectId: 'todo-app-3f236',
    storageBucket: 'todo-app-3f236.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
